#!/usr/bin/env bash
# Generated by: cortex hooks init
# Regenerate:   cortex hooks init --force
#
# PreCompact hook: injects instructions into the compaction prompt asking Claude
# to save a conversation summary to working memory before context is truncated.
# stdout is appended to the compaction instructions Claude receives.

command -v cortex >/dev/null 2>&1 || exit 0

cat <<'CORTEX_HOOKS_PROMPT_END'
Before compacting: please save a summary of this conversation to Cortex working memory using 'cortex consolidate --level working --content "Session summary: <what was accomplished, decisions made, current state, open questions>"'. This preserves context across compaction.
CORTEX_HOOKS_PROMPT_END

exit 0
