#!/usr/bin/env bash
# Generated by: cortex hooks init
# Regenerate:   cortex hooks init --force
#
# SessionStart hook: notifies Claude of available memories without dumping content.
# stdout is injected as Claude Code's initial context.

command -v cortex >/dev/null 2>&1 || exit 0

STATS=$(cortex stats --json 2>/dev/null || true)
if [ -n "$STATS" ]; then
  SEM=$(printf '%s' "$STATS" | grep -o '"semantic":[0-9]*' | grep -o '[0-9]*' || echo 0)
  EPI=$(printf '%s' "$STATS" | grep -o '"episodic":[0-9]*' | grep -o '[0-9]*' || echo 0)
  WRK=$(printf '%s' "$STATS" | grep -o '"working":[0-9]*' | grep -o '[0-9]*' || echo 0)
  echo "# Cortex Memory"
  echo ""
  echo "${SEM} semantic · ${EPI} episodic · ${WRK} working memories stored."
  echo ""
  cat <<'CORTEX_HOOKS_PROMPT_END'
Use 'cortex list --level <semantic|episodic|working>' or 'cortex search "<query>"' to retrieve context as needed.
CORTEX_HOOKS_PROMPT_END
else
  echo "# Cortex Memory"
  echo ""
  echo "Memories may be available. Run 'cortex stats' to check."
fi

exit 0
