#!/usr/bin/env bash
# Generated by: cortex hooks init
# Regenerate:   cortex hooks init --force
#
# Stop hook: one-shot memory-review prompt after each response, then daily autoprune.
#
# Behaviour:
#   1st call per session: block the stop; inject memory-review prompt.
#   2nd call (after Claude acts on the review): allow stop; run daily cleanup.

command -v cortex >/dev/null 2>&1 || exit 0

# Derive session ID from git branch (prefix mode, max 2 segments, separator '-').
SESSION_ID="default"
if command -v git >/dev/null 2>&1; then
  BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
  if [ -n "$BRANCH" ] && [ "$BRANCH" != "HEAD" ]; then
    PART1=$(echo "$BRANCH" | cut -d'/' -f1)
    PART2=$(echo "$BRANCH" | cut -d'/' -f2)
    if [ -n "$PART2" ] && [ "$PART2" != "$PART1" ]; then
      SESSION_ID="session-${PART1}-${PART2}"
    else
      SESSION_ID="session-${PART1}"
    fi
  fi
fi

REVIEW_FLAG="${TMPDIR:-/tmp}/cortex-reviewed-${SESSION_ID}"

# ── One-shot memory review ────────────────────────────────────────────────────
if [ ! -f "$REVIEW_FLAG" ]; then
  touch "$REVIEW_FLAG"
  MSG=$(cat <<'CORTEX_HOOKS_PROMPT_END'
Memory review: Please decide if anything from this session should be saved. Use 'cortex consolidate --level semantic|episodic --content "..."' to create memories, or 'cortex delete <id>' to remove obsolete ones. When done, your next response will end the session normally.
CORTEX_HOOKS_PROMPT_END
  )
  printf '{"decision":"block","reason":"%s"}' \
    "$(printf '%s' "$MSG" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  exit 0
fi

# ── Second call: allow stop + daily autoprune ─────────────────────────────────
rm -f "$REVIEW_FLAG"

MARKER="${HOME}/.cortex_last_autoprune"
NOW=$(date +%s)
RUN_PRUNE=1
if [ -f "$MARKER" ]; then
  LAST=$(cat "$MARKER" 2>/dev/null || echo 0)
  [ $((NOW - LAST)) -lt 86400 ] && RUN_PRUNE=0
fi
[ "$RUN_PRUNE" -eq 1 ] && cortex autoprune >/dev/null 2>&1 && printf '%s' "$NOW" > "$MARKER"

exit 0
