#!/usr/bin/env bash
# Generated by: cortex hooks init
# Regenerate:   cortex hooks init --force
#
# Stop hook: one-shot memory-review prompt after each response, then daily autoprune.
#
# Behaviour:
#   1st call per session: block the stop; inject memory-review prompt.
#   2nd call (after Claude acts on the review): allow stop; run daily cleanup.

command -v cortex >/dev/null 2>&1 || exit 0

SESSION_ID=$(cortex session id 2>/dev/null || echo "default")

REVIEW_FLAG="${TMPDIR:-/tmp}/cortex-reviewed-${SESSION_ID}"

# ── One-shot memory review ────────────────────────────────────────────────────
if [ ! -f "$REVIEW_FLAG" ]; then
  touch "$REVIEW_FLAG"
  MSG=$(cat <<'CORTEX_HOOKS_PROMPT_END'
Memory review: Please save any relevant context from this session to working memory first using 'cortex consolidate --level working --session $SESSION_ID --content "..."'. Then consolidate to episodic memory any completed work, decisions, or outcomes worth keeping in history using 'cortex consolidate --level episodic --content "..."'. Do NOT write directly to semantic memory here — semantic consolidation happens separately via memory maintenance. Use 'cortex delete <id>' to remove obsolete memories. When done, your next response will end the session normally.
CORTEX_HOOKS_PROMPT_END
  )
  printf '{"decision":"block","reason":"%s"}' \
    "$(printf '%s' "$MSG" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  exit 0
fi

# ── Second call: allow stop + daily autoprune ─────────────────────────────────
rm -f "$REVIEW_FLAG"

MARKER="${HOME}/.cortex_last_autoprune"
NOW=$(date +%s)
RUN_PRUNE=1
if [ -f "$MARKER" ]; then
  LAST=$(cat "$MARKER" 2>/dev/null || echo 0)
  [ $((NOW - LAST)) -lt 86400 ] && RUN_PRUNE=0
fi
[ "$RUN_PRUNE" -eq 1 ] && cortex autoprune >/dev/null 2>&1 && printf '%s' "$NOW" > "$MARKER"

exit 0
