run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - linter
    - gofmt
    - goimports
    - gosimple
    - gocritic
    - unused
    - staticcheck

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/cortex-ai/cortex-ai

output:
  format: colored-line-number

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
