package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/cortex-ai/cortex-ai/internal/config"
	"github.com/spf13/cobra"
)

var hooksCmd = &cobra.Command{
	Use:   "hooks",
	Short: "Manage Claude Code hook scripts",
}

var hooksInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate Claude Code hook scripts for automatic memory management",
	Long: `Generate Claude Code hook scripts in .claude/hooks/ with prompts embedded from config.

Scripts generated:
  session-start.sh  Notifies Claude of available memories at session start.
  session-stop.sh   One-shot memory-review prompt after each response + daily autoprune.
  pre-compact.sh    Asks Claude to save a summary before context compaction.

Prompts are read from the Cortex config file (hooks.session_start.notification_prompt,
hooks.stop.review_prompt, hooks.pre_compact.summary_prompt). If not set, defaults are used.

Re-run with --force to overwrite existing scripts.`,
	RunE: runHooksInit,
}

var (
	hooksInitDir   string
	hooksInitForce bool
)

func init() {
	hooksInitCmd.Flags().StringVar(&hooksInitDir, "dir", ".claude", "Target directory for hook files")
	hooksInitCmd.Flags().BoolVar(&hooksInitForce, "force", false, "Overwrite existing scripts")
	hooksCmd.AddCommand(hooksInitCmd)
	rootCmd.AddCommand(hooksCmd)
}

// sessionStartScript builds the session-start.sh content with the given notification prompt.
// Uses a quoted heredoc so the prompt is treated as literal text regardless of content.
func sessionStartScript(notificationPrompt string) string {
	return "#!/usr/bin/env bash\n" +
		"# Generated by: cortex hooks init\n" +
		"# Regenerate:   cortex hooks init --force\n" +
		"#\n" +
		"# SessionStart hook: notifies Claude of available memories without dumping content.\n" +
		"# stdout is injected as Claude Code's initial context.\n" +
		"\n" +
		"command -v cortex >/dev/null 2>&1 || exit 0\n" +
		"\n" +
		"STATS=$(cortex stats --json 2>/dev/null || true)\n" +
		`if [ -n "$STATS" ]; then` + "\n" +
		`  SEM=$(printf '%s' "$STATS" | grep -o '"semantic":[0-9]*' | grep -o '[0-9]*' || echo 0)` + "\n" +
		`  EPI=$(printf '%s' "$STATS" | grep -o '"episodic":[0-9]*' | grep -o '[0-9]*' || echo 0)` + "\n" +
		`  WRK=$(printf '%s' "$STATS" | grep -o '"working":[0-9]*' | grep -o '[0-9]*' || echo 0)` + "\n" +
		`  echo "# Cortex Memory"` + "\n" +
		`  echo ""` + "\n" +
		`  echo "${SEM} semantic · ${EPI} episodic · ${WRK} working memories stored."` + "\n" +
		`  echo ""` + "\n" +
		"  cat <<'CORTEX_HOOKS_PROMPT_END'\n" +
		notificationPrompt + "\n" +
		"CORTEX_HOOKS_PROMPT_END\n" +
		"else\n" +
		`  echo "# Cortex Memory"` + "\n" +
		`  echo ""` + "\n" +
		`  echo "Memories may be available. Run 'cortex stats' to check."` + "\n" +
		"fi\n" +
		"\n" +
		"exit 0\n"
}

// sessionStopScript builds the session-stop.sh content with the given review prompt.
func sessionStopScript(reviewPrompt string) string {
	return "#!/usr/bin/env bash\n" +
		"# Generated by: cortex hooks init\n" +
		"# Regenerate:   cortex hooks init --force\n" +
		"#\n" +
		"# Stop hook: one-shot memory-review prompt after each response, then daily autoprune.\n" +
		"#\n" +
		"# Behaviour:\n" +
		"#   1st call per session: block the stop; inject memory-review prompt.\n" +
		"#   2nd call (after Claude acts on the review): allow stop; run daily cleanup.\n" +
		"\n" +
		"command -v cortex >/dev/null 2>&1 || exit 0\n" +
		"\n" +
		"# Derive session ID from git branch (prefix mode, max 2 segments, separator '-').\n" +
		`SESSION_ID="default"` + "\n" +
		"if command -v git >/dev/null 2>&1; then\n" +
		"  BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)\n" +
		`  if [ -n "$BRANCH" ] && [ "$BRANCH" != "HEAD" ]; then` + "\n" +
		`    PART1=$(echo "$BRANCH" | cut -d'/' -f1)` + "\n" +
		`    PART2=$(echo "$BRANCH" | cut -d'/' -f2)` + "\n" +
		`    if [ -n "$PART2" ] && [ "$PART2" != "$PART1" ]; then` + "\n" +
		`      SESSION_ID="session-${PART1}-${PART2}"` + "\n" +
		"    else\n" +
		`      SESSION_ID="session-${PART1}"` + "\n" +
		"    fi\n" +
		"  fi\n" +
		"fi\n" +
		"\n" +
		`REVIEW_FLAG="${TMPDIR:-/tmp}/cortex-reviewed-${SESSION_ID}"` + "\n" +
		"\n" +
		"# ── One-shot memory review ────────────────────────────────────────────────────\n" +
		`if [ ! -f "$REVIEW_FLAG" ]; then` + "\n" +
		`  touch "$REVIEW_FLAG"` + "\n" +
		"  MSG=$(cat <<'CORTEX_HOOKS_PROMPT_END'\n" +
		reviewPrompt + "\n" +
		"CORTEX_HOOKS_PROMPT_END\n" +
		"  )\n" +
		`  printf '{"decision":"block","reason":"%s"}' \` + "\n" +
		`    "$(printf '%s' "$MSG" | sed 's/\\/\\\\/g; s/"/\\"/g')"` + "\n" +
		"  exit 0\n" +
		"fi\n" +
		"\n" +
		"# ── Second call: allow stop + daily autoprune ─────────────────────────────────\n" +
		`rm -f "$REVIEW_FLAG"` + "\n" +
		"\n" +
		`MARKER="${HOME}/.cortex_last_autoprune"` + "\n" +
		"NOW=$(date +%s)\n" +
		"RUN_PRUNE=1\n" +
		`if [ -f "$MARKER" ]; then` + "\n" +
		`  LAST=$(cat "$MARKER" 2>/dev/null || echo 0)` + "\n" +
		`  [ $((NOW - LAST)) -lt 86400 ] && RUN_PRUNE=0` + "\n" +
		"fi\n" +
		`[ "$RUN_PRUNE" -eq 1 ] && cortex autoprune >/dev/null 2>&1 && printf '%s' "$NOW" > "$MARKER"` + "\n" +
		"\n" +
		"exit 0\n"
}

// preCompactScript builds the pre-compact.sh content with the given summary prompt.
func preCompactScript(summaryPrompt string) string {
	return "#!/usr/bin/env bash\n" +
		"# Generated by: cortex hooks init\n" +
		"# Regenerate:   cortex hooks init --force\n" +
		"#\n" +
		"# PreCompact hook: injects instructions into the compaction prompt asking Claude\n" +
		"# to save a conversation summary to working memory before context is truncated.\n" +
		"# stdout is appended to the compaction instructions Claude receives.\n" +
		"\n" +
		"command -v cortex >/dev/null 2>&1 || exit 0\n" +
		"\n" +
		"cat <<'CORTEX_HOOKS_PROMPT_END'\n" +
		summaryPrompt + "\n" +
		"CORTEX_HOOKS_PROMPT_END\n" +
		"\n" +
		"exit 0\n"
}

const hooksSettingsJSON = `{
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "bash .claude/hooks/session-start.sh"
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "bash .claude/hooks/session-stop.sh"
          }
        ]
      }
    ],
    "PreCompact": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "bash .claude/hooks/pre-compact.sh"
          }
        ]
      }
    ]
  }
}
`

func runHooksInit(cmd *cobra.Command, args []string) error {
	cfg := config.Global()

	hooksDir := filepath.Join(hooksInitDir, "hooks")
	settingsPath := filepath.Join(hooksInitDir, "settings.json")

	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	scripts := []struct {
		name    string
		content string
	}{
		{"session-start.sh", sessionStartScript(cfg.Hooks.SessionStart.NotificationPrompt)},
		{"session-stop.sh", sessionStopScript(cfg.Hooks.Stop.ReviewPrompt)},
		{"pre-compact.sh", preCompactScript(cfg.Hooks.PreCompact.SummaryPrompt)},
	}

	for _, script := range scripts {
		path := filepath.Join(hooksDir, script.name)
		if !hooksInitForce {
			if _, err := os.Stat(path); err == nil {
				_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  skip   %s (already exists; use --force to overwrite)\n", path)
				continue
			}
		}
		if err := os.WriteFile(path, []byte(script.content), 0755); err != nil {
			return fmt.Errorf("failed to write %s: %w", script.name, err)
		}
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  write  %s\n", path)
	}

	if !hooksInitForce {
		if _, err := os.Stat(settingsPath); err == nil {
			_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  skip   %s (already exists; use --force to overwrite)\n", settingsPath)
		} else {
			if err := os.WriteFile(settingsPath, []byte(hooksSettingsJSON), 0644); err != nil {
				return fmt.Errorf("failed to write settings.json: %w", err)
			}
			_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  write  %s\n", settingsPath)
		}
	} else {
		if err := os.WriteFile(settingsPath, []byte(hooksSettingsJSON), 0644); err != nil {
			return fmt.Errorf("failed to write settings.json: %w", err)
		}
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "  write  %s\n", settingsPath)
	}

	_, _ = fmt.Fprintln(cmd.OutOrStdout(), "\nDone. Commit the generated files to your repository.")
	_, _ = fmt.Fprintln(cmd.OutOrStdout(), "Regenerate anytime with: cortex hooks init --force")
	return nil
}
