#!/usr/bin/env bash
# Generated by: cortex hook
# Regenerate:   cortex hook --claude
#
# SessionStart hook: shows active working memories and notifies Claude of available context.
# stdout is injected as Claude Code's initial context.

command -v cortex >/dev/null 2>&1 || exit 0

SESSION_ID=$(cortex session id 2>/dev/null || echo "default")

echo "# Cortex Memory"
echo ""
WORKING=$(cortex list --level working --session "$SESSION_ID" 2>/dev/null || true)
if [ -n "$WORKING" ]; then
  echo "## Active working memories for this session (id · title):"
  echo ""
  cortex list --level working --session "$SESSION_ID" --json 2>/dev/null | \
    grep -E '"id"|"title"' | paste - - | sed 's/.*"id": *"\([^" ]*\)".*"title": *"\([^"]*\)".*/  \1 · \2/' || true
  echo ""
fi

cat <<'CORTEX_HOOKS_PROMPT_END'
Working memories for this session are listed above.
Use 'cortex get <id>' to load the full content of any relevant memory.
Use 'cortex list --level <semantic|episodic|working>' or
  'cortex search "<query>"' to retrieve
additional context as needed.
CORTEX_HOOKS_PROMPT_END

exit 0
