#!/usr/bin/env bash
# Generated by: cortex hooks init --copilot
# Regenerate:   cortex hooks init --copilot --force
#
# sessionStart hook: shows active working memories to stderr at session start.
# Copilot passes event JSON on stdin; stdout is ignored by Copilot.

command -v cortex >/dev/null 2>&1 || exit 0

SESSION_ID=$(cortex session id 2>/dev/null || echo "default")

echo "# Cortex Memory" >&2
echo "" >&2
WORKING=$(cortex list --level working --session "$SESSION_ID" --json 2>/dev/null || true)
if [ -n "$WORKING" ]; then
  echo "## Active working memories for this session (id · title):" >&2
  echo "" >&2
  printf '%s' "$WORKING" | \
    grep -E '"id"|"title"' | paste - - | sed 's/.*"id": *"\\([^"]*\\)".*"title": *"\\([^"]*\\)".*/  \\1 · \\2/' >&2 || true
  echo "" >&2
fi
cat >&2 <<'CORTEX_HOOKS_PROMPT_END'
Working memories for this session are listed above. Use 'cortex get <id>' to load the full content of any relevant memory. Use 'cortex list --level <semantic|episodic|working>' or 'cortex search "<query>"' to retrieve additional context as needed.
CORTEX_HOOKS_PROMPT_END

exit 0
