#!/usr/bin/env bash
# Generated by: cortex hooks init --copilot
# Regenerate:   cortex hooks init --copilot --force
#
# sessionStart hook: logs available Cortex memories to stderr.
# Copilot passes event JSON on stdin; stdout is ignored by Copilot.

command -v cortex >/dev/null 2>&1 || exit 0

STATS=$(cortex stats --json 2>/dev/null || true)
if [ -n "$STATS" ]; then
  SEM=$(printf '%s' "$STATS" | grep -o '"semantic":[[:space:]]*[0-9]*' | grep -o '[0-9]*' || echo 0)
  EPI=$(printf '%s' "$STATS" | grep -o '"episodic":[[:space:]]*[0-9]*' | grep -o '[0-9]*' || echo 0)
  WRK=$(printf '%s' "$STATS" | grep -o '"working":[[:space:]]*[0-9]*' | grep -o '[0-9]*' || echo 0)
  echo "# Cortex Memory: ${SEM} semantic · ${EPI} episodic · ${WRK} working" >&2
  cat >&2 <<'CORTEX_HOOKS_PROMPT_END'
Use 'cortex list --level <semantic|episodic|working>' or 'cortex search "<query>"' to retrieve context as needed.
CORTEX_HOOKS_PROMPT_END
fi

exit 0
