#!/usr/bin/env bash
# Generated by: cortex hooks init --copilot
# Regenerate:   cortex hooks init --copilot --force
#
# sessionEnd hook: runs daily Cortex autoprune.
# Copilot passes event JSON on stdin; stdout is ignored.

command -v cortex >/dev/null 2>&1 || exit 0

MARKER="${HOME}/.cortex_last_autoprune"
NOW=$(date +%s)
RUN_PRUNE=1
if [ -f "$MARKER" ]; then
  LAST=$(cat "$MARKER" 2>/dev/null || echo 0)
  [ $((NOW - LAST)) -lt 86400 ] && RUN_PRUNE=0
fi
[ "$RUN_PRUNE" -eq 1 ] && cortex autoprune >/dev/null 2>&1 && printf '%s' "$NOW" > "$MARKER"

exit 0
