package markdown

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/cortex-ai/cortex-ai/internal/memory"
)

// Exporter exports memories to Markdown files
type Exporter struct {
	outputDir string
}

// NewExporter creates a new Exporter
func NewExporter(outputDir string) *Exporter {
	return &Exporter{
		outputDir: outputDir,
	}
}

// ExportMemory exports a single memory to a Markdown file
// Returns the path of the exported file
func (e *Exporter) ExportMemory(m *memory.Memory) (string, error) {
	if m == nil {
		return "", fmt.Errorf("memory is nil")
	}

	// Ensure output directory exists
	if err := os.MkdirAll(e.outputDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create output directory: %w", err)
	}

	// Convert memory types to string slice
	types := make([]string, len(m.Types))
	for i, t := range m.Types {
		types[i] = string(t)
	}

	// Build frontmatter
	fm := &Frontmatter{
		ID:        m.ID,
		Title:     m.Title,
		Types:     types,
		Tags:      m.Tags,
		CreatedAt: m.CreatedAt,
		UpdatedAt: m.UpdatedAt,
		Obsolete:  m.Obsolete,
		Metadata:  m.Metadata,
	}

	// Format frontmatter
	fmStr, err := FormatFrontmatter(fm)
	if err != nil {
		return "", fmt.Errorf("failed to format frontmatter: %w", err)
	}

	// Build full content
	content := fmStr + "\n" + m.Content

	// Write to file
	filename := fmt.Sprintf("%s.md", m.ID)
	filepath := filepath.Join(e.outputDir, filename)

	if err := os.WriteFile(filepath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write file: %w", err)
	}

	return filepath, nil
}

// ExportAll exports all memories to separate files
// Returns the paths of all exported files
func (e *Exporter) ExportAll(memories []*memory.Memory) ([]string, error) {
	if len(memories) == 0 {
		return nil, nil
	}

	var paths []string
	for _, m := range memories {
		path, err := e.ExportMemory(m)
		if err != nil {
			return paths, fmt.Errorf("failed to export memory %s: %w", m.ID, err)
		}
		paths = append(paths, path)
	}

	return paths, nil
}

// ExportSynthesis generates a synthesis document from search results
func (e *Exporter) ExportSynthesis(intent string, results []*memory.SearchResult) (string, error) {
	if len(results) == 0 {
		return "", fmt.Errorf("no results to synthesize")
	}

	// Ensure output directory exists
	if err := os.MkdirAll(e.outputDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create output directory: %w", err)
	}

	// Build source memories list
	sources := make([]SourceMemory, len(results))
	for i, r := range results {
		sources[i] = SourceMemory{
			ID:    r.Memory.ID,
			Title: r.Memory.Title,
			Score: r.Score,
		}
	}

	// Build synthesis frontmatter
	fm := &SynthesisFrontmatter{
		Type:           "synthesis",
		Intent:         intent,
		GeneratedAt:    time.Now().UTC(),
		SourceMemories: sources,
	}

	// Format frontmatter
	fmStr, err := FormatSynthesisFrontmatter(fm)
	if err != nil {
		return "", fmt.Errorf("failed to format synthesis frontmatter: %w", err)
	}

	// Build synthesis body
	var body strings.Builder

	body.WriteString(fmt.Sprintf("# %s - Synthesis\n\n", toTitleCase(intent)))
	body.WriteString(fmt.Sprintf("This document synthesizes %d memories related to \"%s\".\n\n", len(results), intent))

	body.WriteString("## Summary\n\n")
	body.WriteString("Based on the stored memories, the following information was found:\n\n")

	body.WriteString("## Key Learnings\n\n")
	for _, r := range results {
		body.WriteString(fmt.Sprintf("### From: %s (score: %.2f)\n\n", r.Memory.Title, r.Score))

		// Include a preview of the content (first 500 chars or up to first section)
		preview := getContentPreview(r.Memory.Content, 500)
		body.WriteString(preview)
		body.WriteString("\n\n")
	}

	body.WriteString("---\n\n")
	body.WriteString("*Generated by Cortex AI - This is a read-only synthesis, not importable.*\n")

	// Combine frontmatter and body
	content := fmStr + "\n" + body.String()

	// Write to file
	filename := fmt.Sprintf("synthesis-%s.md", sanitizeFilename(intent))
	filepath := filepath.Join(e.outputDir, filename)

	if err := os.WriteFile(filepath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write synthesis file: %w", err)
	}

	return filepath, nil
}

// toTitleCase converts a string to title case
func toTitleCase(s string) string {
	words := strings.Fields(s)
	for i, word := range words {
		if len(word) > 0 {
			words[i] = strings.ToUpper(string(word[0])) + strings.ToLower(word[1:])
		}
	}
	return strings.Join(words, " ")
}

// getContentPreview returns a preview of the content
func getContentPreview(content string, maxLen int) string {
	if len(content) <= maxLen {
		return content
	}

	// Try to cut at a paragraph boundary
	preview := content[:maxLen]
	if lastPara := strings.LastIndex(preview, "\n\n"); lastPara > maxLen/2 {
		return preview[:lastPara] + "\n\n..."
	}

	// Otherwise cut at word boundary
	if lastSpace := strings.LastIndex(preview, " "); lastSpace > maxLen/2 {
		return preview[:lastSpace] + "..."
	}

	return preview + "..."
}

// sanitizeFilename removes or replaces characters that are invalid in filenames
func sanitizeFilename(s string) string {
	// Replace spaces with hyphens
	s = strings.ReplaceAll(s, " ", "-")
	// Remove characters that are problematic in filenames
	replacer := strings.NewReplacer(
		"/", "",
		"\\", "",
		":", "",
		"*", "",
		"?", "",
		"\"", "",
		"<", "",
		">", "",
		"|", "",
	)
	s = replacer.Replace(s)
	// Convert to lowercase
	s = strings.ToLower(s)
	// Limit length
	if len(s) > 50 {
		s = s[:50]
	}
	return s
}
