"""Install assistant hooks for Cortex integrations."""

from __future__ import annotations

import json
import stat
from pathlib import Path
from typing import Annotated

import typer


def _script(*lines: str) -> str:
    return "\n".join(lines) + "\n"


# Hook names mapped to script filenames
_HOOK_SCRIPTS: dict[str, str] = {
    "session-start.sh": "SessionStart",
    "session-stop.sh": "Stop",
    "pre-compact.sh": "PreCompact",
}

# Base directories per target
_TARGET_DIRS: dict[str, str] = {
    "claude": ".claude",
    "cortex": ".cortex",
    "copilot": ".copilot",
}

# Script templates
_SESSION_START = _script(
    "#!/usr/bin/env bash",
    "# Generated by: cortex hook",
    "# Regenerate:   cortex hook --claude",
    "#",
    "# SessionStart hook: shows active working memories and notifies Claude of available context.",
    "# stdout is injected as Claude Code's initial context.",
    "",
    "command -v cortex >/dev/null 2>&1 || exit 0",
    "",
    'SESSION_ID=$(cortex session id 2>/dev/null || echo "default")',
    "",
    'echo "# Cortex Memory"',
    'echo ""',
    'WORKING=$(cortex list --level working --session "$SESSION_ID" 2>/dev/null || true)',
    'if [ -n "$WORKING" ]; then',
    '  echo "## Active working memories for this session (id · title):"',
    '  echo ""',
    '  cortex list --level working --session "$SESSION_ID" --json 2>/dev/null | \\',
    '    grep -E \'"id"|"title"\' | paste - - | '
    'sed \'s/.*"id": *"\\([^" ]*\\)".*"title": *"\\([^"]*\\)".*/  \\1 · \\2/\' || true',
    '  echo ""',
    "fi",
    "",
    "cat <<'CORTEX_HOOKS_PROMPT_END'",
    "Working memories for this session are listed above.",
    "Use 'cortex get <id>' to load the full content of any relevant memory.",
    "Use 'cortex list --level <semantic|episodic|working>' or",
    "  'cortex search \"<query>\"' to retrieve",
    "additional context as needed.",
    "CORTEX_HOOKS_PROMPT_END",
    "",
    "exit 0",
)

_SESSION_STOP = _script(
    "#!/usr/bin/env bash",
    "# Generated by: cortex hook",
    "# Regenerate:   cortex hook --claude",
    "#",
    "# Stop hook: one-shot memory-review prompt after each response, then daily autoprune.",
    "#",
    "# Behaviour:",
    "#   1st call per session: block the stop; inject memory-review prompt.",
    "#   2nd call (after Claude acts on the review): allow stop; run daily cleanup.",
    "",
    "command -v cortex >/dev/null 2>&1 || exit 0",
    "",
    'SESSION_ID=$(cortex session id 2>/dev/null || echo "default")',
    "",
    'REVIEW_FLAG="${TMPDIR:-/tmp}/cortex-reviewed-${SESSION_ID}"',
    "",
    "# ── One-shot memory review ────────────────────────────────────────────────────",
    'if [ ! -f "$REVIEW_FLAG" ]; then',
    '  touch "$REVIEW_FLAG"',
    "  MSG=$(cat <<'CORTEX_HOOKS_PROMPT_END'",
    "Memory review: Please save any relevant context from this session to working memory first",
    "using 'cortex consolidate --level working --session $SESSION_ID --content \"...\"'. Then",
    "consolidate to episodic memory any completed work, decisions, or outcomes worth keeping in",
    "history using 'cortex consolidate --level episodic --content \"...\"'. Do NOT write directly",
    "to semantic memory here — semantic consolidation happens separately via memory maintenance.",
    "Use 'cortex delete <id>' to remove obsolete memories. When done, your next response will end",
    "the session normally.",
    "CORTEX_HOOKS_PROMPT_END",
    "  )",
    '  printf \'{"decision":"block","reason":"%s"}\' \\',
    '    "$(printf \'%s\' "$MSG" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\"/g\')"',
    "  exit 0",
    "fi",
    "",
    "# ── Second call: allow stop + daily autoprune ─────────────────────────────────",
    'rm -f "$REVIEW_FLAG"',
    "",
    'MARKER="${HOME}/.cortex_last_autoprune"',
    "NOW=$(date +%s)",
    "RUN_PRUNE=1",
    'if [ -f "$MARKER" ]; then',
    '  LAST=$(cat "$MARKER" 2>/dev/null || echo 0)',
    "  [ $((NOW - LAST)) -lt 86400 ] && RUN_PRUNE=0",
    "fi",
    '[ "$RUN_PRUNE" -eq 1 ] && cortex autoprune >/dev/null 2>&1 && \\',
    '  printf \'%s\' "$NOW" > "$MARKER"',
    "",
    "exit 0",
)

_PRE_COMPACT = _script(
    "#!/usr/bin/env bash",
    "# Generated by: cortex hook",
    "# Regenerate:   cortex hook --claude",
    "#",
    "# PreCompact hook: injects instructions into the compaction prompt asking Claude",
    "# to save a conversation summary to working memory before context is truncated.",
    "# stdout is appended to the compaction instructions Claude receives.",
    "",
    "command -v cortex >/dev/null 2>&1 || exit 0",
    "",
    "cat <<'CORTEX_HOOKS_PROMPT_END'",
    "Before compacting: please save a summary of this conversation to Cortex working memory using",
    "'cortex consolidate --level working --content \"Session summary: <what was accomplished,",
    " decisions made, current state, open questions>\"'. This preserves context across compaction.",
    "CORTEX_HOOKS_PROMPT_END",
    "",
    "exit 0",
)

_SCRIPT_CONTENT: dict[str, str] = {
    "session-start.sh": _SESSION_START,
    "session-stop.sh": _SESSION_STOP,
    "pre-compact.sh": _PRE_COMPACT,
}


def hook_cmd(
    global_install: Annotated[
        bool,
        typer.Option(
            "--global/--local",
            help="Install hooks globally in the user config directory or locally in the project.",
        ),
    ] = True,
    claude: Annotated[
        bool, typer.Option("--claude", help="Install hooks for Claude clients.")
    ] = False,
    cortex: Annotated[
        bool, typer.Option("--cortex", help="Install hooks for Cortex clients.")
    ] = False,
    copilot: Annotated[
        bool, typer.Option("--copilot", help="Install hooks for Copilot clients.")
    ] = False,
) -> None:
    """Install Cortex hooks without removing non-Cortex entries."""
    targets = _selected_targets(claude=claude, cortex=cortex, copilot=copilot)
    base_root = Path.home() if global_install else Path.cwd()

    for target in targets:
        _install_hooks(base_root / _TARGET_DIRS[target])
        typer.echo(f"Installed {target} hooks at {base_root / _TARGET_DIRS[target]}")


def _selected_targets(*, claude: bool, cortex: bool, copilot: bool) -> list[str]:
    if not any((claude, cortex, copilot)):
        return ["claude"]
    targets: list[str] = []
    if claude:
        targets.append("claude")
    if cortex:
        targets.append("cortex")
    if copilot:
        targets.append("copilot")
    return targets


def _install_hooks(base_dir: Path) -> None:
    hooks_dir = base_dir / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    for filename, content in _SCRIPT_CONTENT.items():
        script_path = hooks_dir / filename
        script_path.write_text(content, encoding="utf-8")
        _make_executable(script_path)

    settings_path = base_dir / "settings.json"
    settings_data = _load_settings(settings_path)
    settings_data["hooks"] = _merge_hooks(settings_data.get("hooks", {}), hooks_dir)

    with settings_path.open("w", encoding="utf-8") as f:
        json.dump(settings_data, f, indent=2)
        f.write("\n")


def _merge_hooks(existing_hooks: object, hooks_dir: Path) -> dict[str, list[dict[str, object]]]:
    hooks: dict[str, list[dict[str, object]]] = {}
    if isinstance(existing_hooks, dict):
        hooks.update({k: v for k, v in existing_hooks.items() if isinstance(v, list)})

    for filename, hook_name in _HOOK_SCRIPTS.items():
        command = f"bash {hooks_dir / filename}"
        entries = hooks.get(hook_name, [])
        cleaned = [entry for entry in entries if not _is_cortex_entry(entry, command=command)]
        cleaned.append({"hooks": [{"type": "command", "command": command}]})
        hooks[hook_name] = cleaned
    return hooks


def _is_cortex_entry(entry: object, *, command: str) -> bool:
    if not isinstance(entry, dict):
        return False
    entry_hooks = entry.get("hooks")
    if not isinstance(entry_hooks, list):
        return False
    return any(isinstance(hook, dict) and hook.get("command") == command for hook in entry_hooks)


def _load_settings(settings_path: Path) -> dict[str, object]:
    if not settings_path.exists():
        return {}
    try:
        with settings_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _make_executable(path: Path) -> None:
    mode = path.stat().st_mode
    path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
